# GitHub Actions workflow
# https://help.github.com/en/actions/reference
#
# Copyright Subatomix Research Inc.
# SPDX-License-Identifier: ISC

name: Build
run-name: Build

on:
  push:
    branches:
      - main
      - next
      - release/*
    tags:
      - release/*
  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch:
    # no options

env:
  # Minimize noise from dotnet CLI
  DOTNET_NOLOGO: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    #url: https://github.com/actions/virtual-environments

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        #url: https://github.com/actions/checkout

      - name: Configure .NET
        uses: actions/setup-dotnet@v4
        #url: https://github.com/actions/setup-dotnet
        with:
          dotnet-version: 8.0.x

      - name: Build
        shell: pwsh
        id: build
        run: >
          dotnet build src -c Release
          -p:SetGitHubActionsVersion=true
          -p:Branch=${{ github.ref }}
          -p:Counter=${{ github.run_number }}
          -p:RepositoryCommit=${{ github.sha }}
          -p:PackageOutputPath=${{ runner.temp }}/dist

      - name: Note Version
        shell: pwsh
        #url: https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions%23environment-files?tool=powershell#adding-a-job-summary
        run: |
          "Version: ``$env:VERSION``" >> $env:GITHUB_STEP_SUMMARY
        env:
          VERSION: ${{ steps.build.outputs.version }}

      - name: Save Package
        uses: actions/upload-artifact@v4
        #url: https://github.com/actions/upload-artifact
        with:
          name: Packages
          path: ${{ runner.temp }}/dist
          if-no-files-found: error

      - name: Publish Package
        if: startsWith(github.ref, 'refs/tags/release/')
        shell: pwsh
        run: >
          dotnet nuget push "${{ runner.temp }}/dist/*.nupkg"
          -s https://api.nuget.org/v3/index.json
          -k $env:NUGET_API_KEY
          --skip-duplicate
          --no-symbols
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        #url: https://github.com/ncipollo/release-action
        if: startsWith(github.ref, 'refs/tags/release/')
        with:
          name: ${{ steps.build.outputs.version }}
          prerelease: ${{ contains('-', steps.build.outputs.version) }}
          draft: true
          bodyFile: CHANGES.md
          artifacts: ${{ runner.temp }}/dist/*nupkg
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
